#!/usr/bin/env python3
from __future__ import annotations
import copy, importlib.util, json
from pathlib import Path
ROOT=Path('.')
spec=importlib.util.spec_from_file_location('v',ROOT/'tools/validate_drowned_harbor_rights_provenance.py')
v=importlib.util.module_from_spec(spec); assert spec.loader; spec.loader.exec_module(v)
DATA=json.loads((ROOT/v.REGISTER).read_text(encoding='utf-8'))
def reject(name,fn):
 d=copy.deepcopy(DATA); fn(d)
 try: v.validate(d)
 except (v.ValidationError,KeyError,TypeError,IndexError): return
 raise AssertionError(f'mutation survived: {name}')
cases=[
 ('schema',lambda d:d.__setitem__('schema_version',2)),('release',lambda d:d.__setitem__('release_id','DH-RIGHTS-REG-002')),('record',lambda d:d.__setitem__('record_id','DH-RIGHTS-002')),('base',lambda d:d.__setitem__('protected_main_starting_sha','0'*40)),
 ('archive bytes',lambda d:d['package'].__setitem__('bytes',1)),('archive hash',lambda d:d['package'].__setitem__('sha256','0'*64)),('manifest bytes',lambda d:d['package'].__setitem__('manifest_bytes',1)),('manifest hash',lambda d:d['package'].__setitem__('manifest_sha256','0'*64)),('payload count',lambda d:d['package'].__setitem__('manifested_payload_count_excluding_manifest',36)),('missing payload',lambda d:d['package']['missing_payloads'].append('x')),('extra payload',lambda d:d['package']['extra_payloads'].append('x')),('mismatch',lambda d:d['package']['payload_hash_or_byte_mismatches'].append('x')),
 ('status',lambda d:d['disposition'].__setitem__('status','resolved')),('ready',lambda d:d['disposition'].__setitem__('conversion_readiness','ready')),('implementation',lambda d:d['disposition'].__setitem__('implementation_authorized',True)),('prerequisite complete',lambda d:d['disposition'].__setitem__('rights_and_provenance_prerequisite_complete',True)),('pixel use',lambda d:d['disposition'].__setitem__('direct_generated_pixel_use_authorized',True)),('source art',lambda d:d['disposition'].__setitem__('source_art_authorized',True)),('runtime art',lambda d:d['disposition'].__setitem__('runtime_art_authorized',True)),('godot',lambda d:d['disposition'].__setitem__('godot_authorized',True)),('codex',lambda d:d['disposition'].__setitem__('codex_authorized',True)),('candidate',lambda d:d['disposition'].__setitem__('candidate_creation_or_promotion_authorized',True)),('public',lambda d:d['disposition'].__setitem__('public_repository_or_release_assets_authorized',True)),('marketing',lambda d:d['disposition'].__setitem__('marketing_storefront_or_merchandise_authorized',True)),('human',lambda d:d['disposition'].__setitem__('human_evidence_claimed',True)),('accessibility',lambda d:d['disposition'].__setitem__('accessibility_or_readability_claimed',True)),('shipping',lambda d:d['disposition'].__setitem__('production_or_shipping_authorized',True)),
 ('count',lambda d:d['inventory_summary'].__setitem__('unique_image_binary_count',24)),('png count',lambda d:d['inventory_summary'].__setitem__('true_png_count',25)),('jpeg count',lambda d:d['inventory_summary'].__setitem__('jpeg_binary_with_png_filename_count',0)),('jpeg ids',lambda d:d['inventory_summary'].__setitem__('jpeg_binary_with_png_filename_asset_keys',[])),('providers',lambda d:d['inventory_summary'].__setitem__('provider_counts',{'openai':25,'google_gemini':0})),('unknown provider',lambda d:d['inventory_summary'].__setitem__('unknown_provider_count',1)),('c2pa count',lambda d:d['inventory_summary'].__setitem__('locally_detected_openai_c2pa_reference_count_not_authenticated',17)),('c2pa ids',lambda d:d['inventory_summary'].__setitem__('locally_detected_openai_c2pa_reference_asset_keys',[])),('openai attribution',lambda d:d['inventory_summary'].__setitem__('openai_source_attribution_only_asset_keys',[])),('gemini attribution',lambda d:d['inventory_summary'].__setitem__('gemini_source_attribution_asset_keys',[])),('dedup',lambda d:d['inventory_summary'].__setitem__('duplicate_sha256_group_count',1)),
 ('drop asset',lambda d:d['assets'].pop()),('reorder',lambda d:d['assets'].reverse()),('hash',lambda d:d['assets'][0].__setitem__('sha256','0'*64)),('lifecycle',lambda d:d['assets'][0].__setitem__('id','EXT-VIS-999')),('tier',lambda d:d['assets'][0].__setitem__('format','JPEG')),('R2',lambda d:d['assets'][0].__setitem__('classification','gemini_source_attribution_only')),('asset pixel',lambda d:d['assets'][0].__setitem__('provider','google_gemini')),('asset source',lambda d:d['assets'][0].__setitem__('bytes',1)),('asset runtime',lambda d:d['assets'][0].__setitem__('dimensions',[1,1])),('asset candidate',lambda d:d['assets'][0].__setitem__('filename','x.png')),('asset public',lambda d:d['assets'][1].__setitem__('classification','openai_c2pa_reference_detected_not_authenticated')),('asset marketing',lambda d:d['assets'][20].__setitem__('format','PNG')),('attestation',lambda d:d['assets'][18].__setitem__('classification','openai_source_attribution_only')),('format extension',lambda d:d['assets'][17].__setitem__('classification','openai_source_attribution_only')),
 ('images in git',lambda d:d['external_binary_policy'].__setitem__('images_in_git',True)),('archive in git',lambda d:d['external_binary_policy'].__setitem__('archive_in_git',True)),('release assets',lambda d:d['external_binary_policy'].__setitem__('public_github_release_assets',True)),('naming gate',lambda d:d['governance'].__setitem__('naming_gate_issue',8)),('human gate',lambda d:d['governance'].__setitem__('human_evidence_gate_issue',40)),('pr32',lambda d:d['governance'].__setitem__('unrelated_pull_request_excluded',31)),('default tale',lambda d:d['governance'].__setitem__('lantern_house_remains_sole_normal_default_tale',False)),('export',lambda d:d['governance'].__setitem__('drowned_harbor_remains_developer_only_and_ordinary_export_excluded',False)),('remove prerequisite',lambda d:d.__setitem__('remaining_prerequisites',[])),
]
for n,f in cases: reject(n,f)
print(f'Validated {len(cases)} fail-closed DH-RIGHTS-REG-001 mutations')
